# Generated by Django 4.2.3 on 2023-08-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Last Name')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True, unique=True, verbose_name='Price')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Address')),
                ('client_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Client Email')),
                ('client_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Phone')),
                ('client_car', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car')),
                ('client_car_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Model')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(null=True, verbose_name='Invoice Date')),
                ('invoice_due_date', models.DateField(null=True, verbose_name='Invoice Due Date')),
                ('paid', models.BooleanField(blank=True, default=False, verbose_name='Paid')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('line_one_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_one_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_one_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_two_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_two_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_two_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_three_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_three_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_three_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_four_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_four_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_four_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_five_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_five_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_five_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_six_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_six_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_six_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_seven_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_seven_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_seven_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_eight_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_eight_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_eight_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_nine_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_nine_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_nine_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_ten_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_ten_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('line_ten_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Subtotal')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Discount')),
                ('vat', models.IntegerField(blank=True, null=True, verbose_name='VAT')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Total')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', to_field='full_name', verbose_name='Client')),
                ('line_eight', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_eight', to='management.product', verbose_name='Line 8')),
                ('line_five', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_five', to='management.product', verbose_name='Line 5')),
                ('line_four', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_four', to='management.product', verbose_name='Line 4')),
                ('line_nine', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_nine', to='management.product', verbose_name='Line 9')),
                ('line_one', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_one', to='management.product', verbose_name='Line 1')),
                ('line_seven', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_seven', to='management.product', verbose_name='Line 7')),
                ('line_six', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_six', to='management.product', verbose_name='Line 6')),
                ('line_ten', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_ten', to='management.product', verbose_name='Line 10')),
                ('line_three', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_three', to='management.product', verbose_name='Line 3')),
                ('line_two', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_two', to='management.product', verbose_name='Line 2')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-id'],
            },
        ),
    ]
