# Generated by Django 4.2.3 on 2023-08-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_unit_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_one_unit_price',
            field=models.ManyToManyField(blank=True, default=0, null=True, to='management.product'),
        ),
    ]
