# Generated by Django 4.2.3 on 2023-08-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_invoice_line_one_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_one_unit_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product', to_field='price'),
        ),
    ]
