# Generated by Django 4.2.3 on 2023-08-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100, null=True, verbose_name='Car')),
                ('car_model', models.CharField(max_length=100, null=True, verbose_name='Car Model')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('finished', models.BooleanField(blank=True, default=False, verbose_name='Finished')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', to_field='full_name', verbose_name='Client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-id'],
            },
        ),
    ]
