# Generated by Django 4.2.3 on 2023-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Last Name')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Full Name')),
                ('ci', models.CharField(max_length=100, null=True, verbose_name='Cedula de Identidad')),
                ('rif', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro unico de Informacion Fiscal')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
                ('others_datas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Others Datas')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-id'],
            },
        ),
    ]
